# country code      : iso country code, 2 characters
# postal code       : varchar(20)
# place name        : varchar(180)
# admin name1       : 1. order subdivision (state) varchar(100)
# admin code1       : 1. order subdivision (state) varchar(20)
# admin name2       : 2. order subdivision (county/province) varchar(100)
# admin code2       : 2. order subdivision (county/province) varchar(20)
# admin name3       : 3. order subdivision (community) varchar(100)
# admin code3       : 3. order subdivision (community) varchar(20)
# latitude          : estimated latitude (wgs84)
# longitude         : estimated longitude (wgs84)
# accuracy          : accuracy of lat/lng from 1=estimated, 4=geonameid, 6=centroid of addresses or shape

columns:
  - country_code
  - postal_code
  - place_name
  - admin_name_1
  - admin_code_1
  - admin_name_2
  - admin_code_2
  - admin_name_3
  - admin_code_3
  - latitude
  - longitude
  - accuracy

input_filepath: ../input/us_zipcodes.csv
market_filepath: ../input/nielsen-dma-markets.geo.json 
output_filepath: ../output/postal_codes_to_markets.csv
separator: "\t"
